<a href="https://colab.research.google.com/github/Hrithik2212/PyTorch-Deep-Learning-/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

In [ ]:
print(torch.__version__)

1.12.0+cu113


## Introduction to Tensors 

### Creating a Tensor

In [ ]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector 
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# Matrix
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[0][2]

tensor(3)

### Random Tensors 

In [ ]:
torch.rand(3,3,3)

tensor([[[0.0325, 0.1468, 0.4623],
         [0.0120, 0.5286, 0.2249],
         [0.6576, 0.9906, 0.6747]],

        [[0.1732, 0.9559, 0.1976],
         [0.2603, 0.3885, 0.7763],
         [0.3044, 0.6170, 0.3431]],

        [[0.5542, 0.4708, 0.0648],
         [0.0108, 0.6321, 0.5065],
         [0.8211, 0.1834, 0.7802]]])

### Zeros and Ones 

In [ ]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Creating a tensor with range  

In [ ]:
Range_tensor = torch.arange(0,9)
Range_tensor_reshaped = Range_tensor.reshape(3,3)

In [ ]:
zeor_like = torch.zeros_like(Range_tensor_reshaped)
zeor_like

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
zeor_like + 1

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## Tensor Operations 

### Mathematic Operation 

In [ ]:
# Include basic mathematical operation 
# Includes matrix operations 

In [ ]:
matrix + 3

tensor([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
matrix -3

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [ ]:
matrix * 0.5

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]])

In [ ]:
matrix/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000],
        [2.3333, 2.6667, 3.0000]])

In [ ]:
matrix + vector 

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

### Matrix Operation 

In [ ]:
# Element wise Multiplication 
m1 = torch.arange(0,9).reshape(3,3)
m2 = torch.arange(9,18).reshape(3,3)
m1 * m2

tensor([[  0,  10,  22],
        [ 36,  52,  70],
        [ 90, 112, 136]])

In [ ]:
# Dot product 
torch.matmul(m1,m2)

tensor([[ 42,  45,  48],
        [150, 162, 174],
        [258, 279, 300]])

In [ ]:
# Dot Product with numpy 
np.dot(np.array(m1),np.array(m2))

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [ ]:
# Trying with Transpose 
torch.matmul(m1,m2.T)

tensor([[ 32,  41,  50],
        [122, 158, 194],
        [212, 275, 338]])

## Tensor Aggregation 
#### Going from large numbers to small numbers 

### Basic 

In [ ]:
m2

tensor([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [ ]:
m2.min()

tensor(9)

In [ ]:
m2.max()

tensor(17)

### Statiscal

In [ ]:
torch.mean(m2.type(torch.float32))

tensor(13.)

In [ ]:
m1.sum()

tensor(36)

### Complex

In [ ]:
m1.argmin()

tensor(0)

In [ ]:
m2.argmax()

tensor(8)

## Tensor Modification 

* torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
* torch.Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
* torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
* torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

### Reshaping 

In [ ]:
m1 = m1.reshape(1,9)
m1

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
m2.reshape(-1,1)

tensor([[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17]])

In [ ]:
m2.reshape(1,-1)

tensor([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]])