<a href="https://colab.research.google.com/github/Hrithik2212/PyTorch-Deep-Learning-/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

In [3]:
print(torch.__version__)

1.12.0+cu113


## Introduction to Tensors 

### Creating a Tensor

In [4]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# vector 
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([3])

In [10]:
# Matrix
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 3])

In [13]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matrix[0][2]

tensor(3)

### Random Tensors 

In [15]:
torch.rand(3,3,3)

tensor([[[0.5655, 0.4806, 0.7799],
         [0.1750, 0.8683, 0.2042],
         [0.8157, 0.8796, 0.0240]],

        [[0.7228, 0.6614, 0.5497],
         [0.7401, 0.3001, 0.7622],
         [0.8086, 0.7545, 0.6325]],

        [[0.8487, 0.6524, 0.4696],
         [0.3692, 0.2673, 0.8348],
         [0.0092, 0.8195, 0.7283]]])

### Zeros and Ones 

In [16]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Creating a tensor with range  

In [19]:
Range_tensor = torch.arange(0,9)
Range_tensor_reshaped = Range_tensor.reshape(3,3)

In [20]:
zeor_like = torch.zeros_like(Range_tensor_reshaped)
zeor_like

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [21]:
zeor_like + 1

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## Tensor Operations 

### Mathematic Operation 

In [22]:
# Include basic mathematical operation 
# Includes matrix operations 

In [23]:
matrix + 3

tensor([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [24]:
matrix -3

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [25]:
matrix * 0.5

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]])

In [26]:
matrix/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000],
        [2.3333, 2.6667, 3.0000]])

In [27]:
matrix + vector 

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

### Matrix Operation 

In [28]:
# Element wise Multiplication 
m1 = torch.arange(0,9).reshape(3,3)
m2 = torch.arange(9,18).reshape(3,3)
m1 * m2

tensor([[  0,  10,  22],
        [ 36,  52,  70],
        [ 90, 112, 136]])

In [29]:
# Dot product 
torch.matmul(m1,m2)

tensor([[ 42,  45,  48],
        [150, 162, 174],
        [258, 279, 300]])

In [30]:
# Dot Product with numpy 
np.dot(np.array(m1),np.array(m2))

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [31]:
# Trying with Transpose 
torch.matmul(m1,m2.T)

tensor([[ 32,  41,  50],
        [122, 158, 194],
        [212, 275, 338]])

## Tensor Aggregation 
#### Going from large numbers to small numbers 

### Basic 

In [32]:
m2

tensor([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [33]:
m2.min()

tensor(9)

In [34]:
m2.max()

tensor(17)

### Statiscal

In [35]:
torch.mean(m2.type(torch.float32))

tensor(13.)

In [36]:
m1.sum()

tensor(36)

### Complex

In [37]:
m1.argmin()

tensor(0)

In [38]:
m2.argmax()

tensor(8)

## Tensor Modification 

* torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
* torch.Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
* torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
* torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

### Reshaping 

In [39]:
m1 = m1.reshape(1,9)
m1

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [40]:
m2.reshape(-1,1)

tensor([[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17]])

In [41]:
m2.reshape(1,-1)

tensor([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [49]:
m1 = torch.rand((3,3,3))
m1

tensor([[[0.4445, 0.9103, 0.4318],
         [0.8219, 0.2291, 0.9785],
         [0.6859, 0.9006, 0.7585]],

        [[0.5682, 0.7862, 0.7956],
         [0.5895, 0.7222, 0.1533],
         [0.0013, 0.5784, 0.7196]],

        [[0.9178, 0.8844, 0.5941],
         [0.1607, 0.0663, 0.9621],
         [0.7255, 0.5428, 0.3135]]])

In [54]:
m = m1.reshape((9,1,-1))
m

tensor([[[0.4445, 0.9103, 0.4318]],

        [[0.8219, 0.2291, 0.9785]],

        [[0.6859, 0.9006, 0.7585]],

        [[0.5682, 0.7862, 0.7956]],

        [[0.5895, 0.7222, 0.1533]],

        [[0.0013, 0.5784, 0.7196]],

        [[0.9178, 0.8844, 0.5941]],

        [[0.1607, 0.0663, 0.9621]],

        [[0.7255, 0.5428, 0.3135]]])

### Veiwing 

In [55]:
z = m1.view((9,1,-1))
z

tensor([[[0.4445, 0.9103, 0.4318]],

        [[0.8219, 0.2291, 0.9785]],

        [[0.6859, 0.9006, 0.7585]],

        [[0.5682, 0.7862, 0.7956]],

        [[0.5895, 0.7222, 0.1533]],

        [[0.0013, 0.5784, 0.7196]],

        [[0.9178, 0.8844, 0.5941]],

        [[0.1607, 0.0663, 0.9621]],

        [[0.7255, 0.5428, 0.3135]]])

In [58]:
id(z) , id(m1)

(140059727191408, 140059727079568)

### Stack

In [63]:
m3 = torch.stack([m1,m1,m1])
m3

tensor([[[[0.4445, 0.9103, 0.4318],
          [0.8219, 0.2291, 0.9785],
          [0.6859, 0.9006, 0.7585]],

         [[0.5682, 0.7862, 0.7956],
          [0.5895, 0.7222, 0.1533],
          [0.0013, 0.5784, 0.7196]],

         [[0.9178, 0.8844, 0.5941],
          [0.1607, 0.0663, 0.9621],
          [0.7255, 0.5428, 0.3135]]],


        [[[0.4445, 0.9103, 0.4318],
          [0.8219, 0.2291, 0.9785],
          [0.6859, 0.9006, 0.7585]],

         [[0.5682, 0.7862, 0.7956],
          [0.5895, 0.7222, 0.1533],
          [0.0013, 0.5784, 0.7196]],

         [[0.9178, 0.8844, 0.5941],
          [0.1607, 0.0663, 0.9621],
          [0.7255, 0.5428, 0.3135]]],


        [[[0.4445, 0.9103, 0.4318],
          [0.8219, 0.2291, 0.9785],
          [0.6859, 0.9006, 0.7585]],

         [[0.5682, 0.7862, 0.7956],
          [0.5895, 0.7222, 0.1533],
          [0.0013, 0.5784, 0.7196]],

         [[0.9178, 0.8844, 0.5941],
          [0.1607, 0.0663, 0.9621],
          [0.7255, 0.5428, 0.3135]]]])

### Squeeze and Unsqueeze"

In [66]:
m4 = torch.squeeze(m3)
m4.shape , m3.shape

(torch.Size([3, 3, 3, 3]), torch.Size([3, 3, 3, 3]))

In [69]:
m5 = torch.unsqueeze(m3 , dim=0)
m5.shape ,  m3.shape


(torch.Size([1, 3, 3, 3, 3]), torch.Size([3, 3, 3, 3]))

In [70]:
m5.squeeze(dim=0).shape

torch.Size([3, 3, 3, 3])

### Permute

In [71]:
x = torch.randn([2,3,5])
x

tensor([[[-0.2387,  0.2204, -0.4703, -2.0404, -0.6319],
         [-0.3656, -0.0516,  0.5089,  0.7568,  0.7447],
         [-1.6842, -0.6953,  0.8829,  0.5567,  0.1290]],

        [[ 1.5970,  0.0440,  0.9737, -0.0482,  0.6393],
         [-0.7698, -0.3682,  2.1356, -0.3460,  0.5496],
         [ 1.8261,  0.3136,  0.5044,  0.6704, -0.5754]]])

In [72]:
x.permute(2,0,1) , x.permute(2,0,1).shape

(tensor([[[-0.2387, -0.3656, -1.6842],
          [ 1.5970, -0.7698,  1.8261]],
 
         [[ 0.2204, -0.0516, -0.6953],
          [ 0.0440, -0.3682,  0.3136]],
 
         [[-0.4703,  0.5089,  0.8829],
          [ 0.9737,  2.1356,  0.5044]],
 
         [[-2.0404,  0.7568,  0.5567],
          [-0.0482, -0.3460,  0.6704]],
 
         [[-0.6319,  0.7447,  0.1290],
          [ 0.6393,  0.5496, -0.5754]]]), torch.Size([5, 2, 3]))

## GPU Specs 

In [1]:
!nvidia-smi

Fri Jul 29 08:21:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
torch.cuda.device_count()

1

In [6]:
device = 'cuda' if torch.has_cuda else 'cpu'
device

'cuda'